services:
  app:
    build:
      context: .
    container_name: coworking-be
    ports:
      - "8000:8000"  # Exponiendo el puerto de la app
    env_file:
      - .env         # Archivo de variables de entorno
    volumes:
      - .:/app       # Volumen para montar el código local
    depends_on:
      - db           # Espera a que el servicio `db` esté listo

  db:
    image: postgres:14
    container_name: coworking-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: 5434  # Cambia el puerto de escucha interno
    ports:
      - "5434:5434"  # Mapea puerto interno 5434 al externo 5434
    command: postgres -c port=5434
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: